name: Create Extension Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod 
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for changelog generation
        
    - name: Generate Changelog
      uses: orhun/git-cliff-action@v4
      id: git-cliff
      with:
        config: cliff.toml
        args: --latest --tag ${GITHUB_REF_NAME} 
      env:
        OUTPUT: CHANGELOG.md
    - name: Setup Node.js
      id: setup_node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Build extension
      run: npm run build
      
    - name: Update manifest version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        jq --arg version "$VERSION" '.version = $version' manifest.json > manifest.json.tmp
        mv manifest.json.tmp manifest.json
      
    - name: Create extension zip
      run: |
        zip -r demoflio-extension.zip manifest.json html/ dist/ demos/ pictures/ assets/ -x "assets/data.json"
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: demoflio-extension.zip
        draft: false
        prerelease: false
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}